workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    clerk-openapi:
        inputs:
            - location: https://raw.githubusercontent.com/clerk/openapi-specs/refs/heads/main/bapi/2024-10-01.yml
        overlays:
            - location: .speakeasy/overlays/deprecations.yaml
            - location: .speakeasy/overlays/enums.yaml
            - location: .speakeasy/overlays/nullable-values.yaml
            - location: .speakeasy/overlays/name-overrides.yaml
            - location: .speakeasy/overlays/error-responses.yaml
            - location: .speakeasy/overlays/globals.yaml
        registry:
            location: registry.speakeasyapi.dev/clerk/clerk/clerk-openapi
targets:
    clerk-ruby:
        target: ruby
        source: clerk-openapi
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/clerk/clerk/clerk-ruby-code-samples
            blocking: false
