overlay: 1.0.0
info:
  title: Remove Nullable Values (Not Supported in Ruby)
  version: 0.0.1
actions:
  - target: "$.components.schemas[*].properties[*].nullable"
    remove: true

  - target: $.paths[*][*].responses[*].content["application/json"].schema.items.properties[*].nullable
    remove: true

  - target: $.components.responses[*].content["application/json"].schema.properties[*].nullable
    remove: true

  - target: $.paths[*][*].responses[*].content["application/json"].schema.properties[*].properties[*].nullable
    remove: true

  - target: $.paths[*][*].responses[*].content["application/json"].schema.items.properties[*].nullable
    remove: true

  - target: $.paths[*][*].requestBody.content["application/json"].schema.properties[*].nullable
    remove: true

  - target: $.paths[*][*].requestBody.content["application/json"].schema.items.properties[*].nullable
    remove: true
